# Minecraft & Fabric Properties
org.gradle.jvmargs=-Xmx2G

# Minecraft & Loom setup
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.8
loader_version=0.16.14

# Mod Properties
mod_version=1.0.0
maven_group=com.minegens.autoupgrade
archives_base_name=minegens-auto-upgrade

# Dependencies
fabric_version=0.128.2+1.21.7
